apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fitbit-exporter
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - env:
            - name: FITBIT_TIMEZONE
              value: ''
            - name: FITBIT_LANGUAGE
              value: ''
            - name: FITBIT_CLIENT_ID
              value: ''
            - name: FITBIT_CLIENT_SECRET
              value: ''
            - name: FITBIT_ACCESS_TOKEN
              value: ''
            - name: FITBIT_INITIAL_CODE
              value: ''
            - name: REDIRECT_URI
              value: http://127.0.0.1:8080/
            - name: INFLUXDB_HOST
              value: ''
            - name: INFLUXDB_PORT
              value: ''
            - name: INFLUXDB_USERNAME
              value: ''
            - name: INFLUXDB_PASSWORD
              value: ''
            - name: INFLUXDB_DATABASE
              value: ''
            image: alexxanddr/fitbit-exporter:latest
            imagePullPolicy: Always
            name: fitbit-exporter
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 50 23 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
